# Generated by Django 5.2.10 on 2026-03-22 11:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cancel_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bill_type', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receiver_account', models.CharField(blank=True, default='', max_length=20)),
                ('receiver_bank', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('PENDING_OTP', 'Pending OTP Verification'), ('PENDING_HIGH', 'Pending – High Risk Delay'), ('SUCCESS', 'Success'), ('HIGH_RISK_VERIFIED', 'High Risk Verified & Executed'), ('SUSPICIOUS', 'Suspicious (Cancelled)'), ('BLOCKED', 'Blocked – Confirmed Fraud'), ('FAILED', 'Failed')], default='PENDING_OTP', max_length=25)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('risk_score', models.IntegerField(default=0)),
                ('classification', models.CharField(choices=[('SAFE', 'Safe'), ('HIGH_RISK', 'High Risk Verified'), ('SUSPICIOUS', 'Suspicious'), ('FRAUD', 'Confirmed Fraud'), ('PENDING', 'Pending')], default='PENDING', max_length=15)),
                ('explanation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execute_after', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('pin_verified', models.BooleanField(default=False)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('admin_classified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classified_txns', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
